# Generated by Django 3.2.5 on 2021-07-31 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioapp', '0004_video'),
    ]

    operations = [
        migrations.CreateModel(
            name='Music',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('music_key', models.CharField(max_length=12)),
            ],
        ),
        migrations.DeleteModel(
            name='Video',
        ),
    ]
