# Generated by Django 3.2.5 on 2021-07-31 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioapp', '0005_auto_20210731_1722'),
    ]

    operations = [
        migrations.AddField(
            model_name='music',
            name='singer',
            field=models.CharField(default='', max_length=200),
        ),
    ]
