# Generated by Django 3.2.5 on 2021-07-31 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioapp', '0008_auto_20210731_1818'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='singer',
            field=models.CharField(max_length=200),
        ),
    ]
