# Generated by Django 3.2.5 on 2021-07-31 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioapp', '0010_visit'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='lyrics',
            field=models.TextField(default=''),
        ),
    ]
