# Generated by Django 3.2.5 on 2021-07-31 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioapp', '0011_post_lyrics'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='lyrics',
        ),
    ]
